version: '3'
services:
  mysql:
    build:
      dockerfile: ./docker/mysql.dockerfile
    container_name: mysql_service
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: board_user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: board
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
  # api:
  #   build:
  #     dockerfile: ./docker/api.dockerfile
  #   ports:
  #     - "3000:3000"
  #   links:
  #     - mysql
