-- MySQL Script generated by MySQL Workbench
-- Sat Mar 26 02:27:35 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema board
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema board
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `board` DEFAULT CHARACTER SET utf8 ;
USE `board` ;

-- -----------------------------------------------------
-- Table `board`.`Board`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `board`.`Board` (
  `idx` INT NOT NULL AUTO_INCREMENT,
  `userName` VARCHAR(50) NOT NULL,
  `password` VARCHAR(200) NOT NULL,
  `title` VARCHAR(100) NOT NULL,
  `contents` TEXT NOT NULL,
  `regDate` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updDate` TIMESTAMP NULL ON UPDATE CURRENT_TIMESTAMP,
  `keyword` JSON NULL,
  `isDel` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`idx`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `board`.`Comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `board`.`Comment` (
  `idx` INT NOT NULL AUTO_INCREMENT,
  `boardIdx` INT NOT NULL,
  `parentIdx` INT NULL DEFAULT NULL,
  `depth` INT NOT NULL,
  `sort` INT NOT NULL,
  `contents` TEXT NOT NULL,
  `userName` VARCHAR(50) NOT NULL,
  `password` VARCHAR(200) NOT NULL,
  `regDate` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `keyword` JSON NULL,
  INDEX `fk_comment_board_idx` (`boardIdx` ASC),
  PRIMARY KEY (`idx`),
  INDEX `fk_comment_comment1_idx` (`parentIdx` ASC),
  CONSTRAINT `fk_comment_board`
    FOREIGN KEY (`boardIdx`)
    REFERENCES `board`.`Board` (`idx`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comment_comment1`
    FOREIGN KEY (`parentIdx`)
    REFERENCES `board`.`Comment` (`idx`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `board`.`Notice`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `board`.`Notice` (
  `idx` INT NOT NULL AUTO_INCREMENT,
  `userName` VARCHAR(50) NOT NULL,
  `contents` TEXT NOT NULL,
  `targetUrl` VARCHAR(255) NULL,
  `regDate` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `readDate` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`idx`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `board`.`Keyword`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `board`.`Keyword` (
  `idx` INT NOT NULL AUTO_INCREMENT,
  `userName` VARCHAR(50) NOT NULL,
  `keyword` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idx`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
